name = "SimulatedAnnealing"
uuid = "119b26b8-39d9-4e2d-8f08-406d7b73be9f"
authors = ["Beno√Æt Richard <kolaru@hotmail.com>"]
version = "0.1.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
